language: python
python:
  - "2.7"
  - "3.4"

install:
  - cd src
  - pip install coveralls
  - cd ..

script:
  - cd src
  - touch .coverage
  - nosetests --with-coverage --cover-package=data_api
  - cd ..

after_success:
  - cd src
  - coveralls
  - cd ..
