language: python
python:
  - "2.7"

install:
  - "mv requirements.txt requirements.txt-"
  - "cp requirements-travis.txt requirements.txt"
  - "python setup.py install"
 #"pip install -r requirements-travis.txt"

script:
  - cd lib
  - touch .coverage
  - nosetests --with-coverage --cover-inclusive --cover-package=data_api --ws-url=test_data  --wsfile-msgpack
  - cd ..

#after_success:
#  - cd lib
#  - coveralls
#  - cd ..
