language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt

script:
  - cd lib
  - touch .coverage
  - nosetests --with-coverage --cover-package=data_api
  - cd ..

after_success:
  - cd lib
  - coveralls
  - cd ..
