language: python
python:
  - "2.7"
  - "3.4"
before_install: cd src
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script: cd src
script: nosetests
after_success: coveralls
