language: python
python:
  - "2.7"

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - "mv requirements.txt requirements.txt-"
  - "cp requirements-travis.txt requirements.txt"
  - "python setup.py install"
 #"pip install -r requirements-travis.txt"

script:
  - cd lib
  - touch .coverage
  - ls -ltR
  - cd ..
  - nosetests --ws-url=test_resources/data  --wsfile-msgpack

#after_success:
#  - cd lib
#  - coveralls
#  - cd ..
